### ISSUE TITLE
use indexOf vs .some

### ISSUE THREAD

**Issue by tuxrace** [tuxrace/rdash#17]
@sudogem performance wise what should we use? indexOf vs .some, this is in relation to the contains function, here is a benchmark guide https://jsperf.com/indexof-vs-somef, what do you guys think?

**Comment by sudogem** [comment]
@tuxrace indexOf looks good..

**Comment by tuxrace** [comment]
I am closing this issue, I have changed the contains function to use indexOf() instead of some().
