### ISSUE TITLE
update readme with newly added functions

### ISSUE THREAD

**Issue by tuxrace** [tuxrace/rdash#26]
@sudogem can you handle this?, thanks

**Comment by sudogem** [comment]
ok.. i'll update our readme.

**Comment by tuxrace** [comment]
OK, you can check here the latest functions list, as of April 15, 2017

1. contains
2. cumSum
3. duplicates
4. factorial
5. groupBY
6. groupBySumAt
7. isPrime
8. sort
9. uniq

**Comment by tuxrace** [comment]
Is this done? @sudogem

**Comment by tuxrace** [comment]
closing this.
